### ISSUE TITLE
已star

### ISSUE THREAD

**Issue by milomoon** [oliverkirk-sudo/WarpGPT#1]
请问作者，可以用access转成sess的key吗？

**Comment by oliverkirk-sudo** [comment]
可以accesskey转api

**Comment by milomoon** [comment]
大佬，我现在登录所有接口都是404。。。不知道有哪个地方需要注意的。。

**Comment by milomoon** [comment]
另外，大佬，有联系方式吗？方便沟通呀。要不你拉个群？

**Comment by oliverkirk-sudo** [comment]
看看你的配置文件，还有这个要搭建在国外有权限访问gpt的服务器上，我没创群聊

**Comment by oliverkirk-sudo** [comment]
联系加我q：609923924
