### ISSUE TITLE
能否将Access-token放在服务端而不是在客户端使用？

### ISSUE THREAD

**Issue by shentong0722** [oliverkirk-sudo/WarpGPT#11]
能不能直接把Access-token或者其他可用的方式写进环境变量之类的？
在客户端填这么一长串比较麻烦
还有，这个调用/r/v1的普通3.5接口会有速率限制吗？

**Comment by oliverkirk-sudo** [comment]
如果直接写进代码，且不开启authkey的话可能造成安全问题

**Comment by oliverkirk-sudo** [comment]
这个程序主要是逆向代理前端GPT，如果需要使用的话可以尝试chatgpt-next-web
