### ISSUE TITLE
使用ws连接，每次回复后SSEClient都会报一次error

### ISSUE THREAD

**Issue by longlegmax** [oliverkirk-sudo/WarpGPT#16]
报错日志如下：

> DEBU[2024-02-20 11:12:20] CopyResponseHeaders
DEBU[2024-02-20 11:12:20] UnofficialApiProcess streamResponse
DEBU[2024-02-20 11:12:20] wss to stream
DEBU[2024-02-20 11:12:20] Read
DEBU[2024-02-20 11:12:20] Read
DEBU[2024-02-20 11:12:20] getStreamResp
DEBU[2024-02-20 11:12:20] Read
DEBU[2024-02-20 11:12:20] getStreamResp
DEBU[2024-02-20 11:12:20] Read
DEBU[2024-02-20 11:12:20] getStreamResp
DEBU[2024-02-20 11:12:20] Read
SSEClient: 2024/02/20 11:12:21 Error reading from event source: read tcp 127.0.0.1:1626->127.0.0.1:10809: use of closed network connection
DEBU[2024-02-20 11:12:21] getStreamResp
[GIN] 2024/02/20 - 11:12:21 | 200 |  2.592412808s |    111.111.11.111 | POST     "/r/v1/chat/completions/ws"

**Comment by oliverkirk-sudo** [comment]
正常的，sseclient不会自动关闭请求，我直接把ws连接关闭了就会报这个错

**Comment by longlegmax** [comment]
原来如此，多谢解答
