### ISSUE TITLE
wss存在未关闭的情况吗

### ISSUE THREAD

**Issue by clcc2019** [oliverkirk-sudo/WarpGPT#24]
<img width="1482" alt="image" src="https://github.com/oliverkirk-sudo/WarpGPT/assets/46099295/cd942567-2d43-49a4-ae4a-2c0e11bad4e0">
十几分钟都未关闭连接

**Comment by oliverkirk-sudo** [comment]
每次请求都会启动ws，输出结束就断开ws

**Comment by clcc2019** [comment]
错误率有点高，同一个token注册wss经常403
