### ISSUE TITLE
proxy_pool_url的格式是什么样的呀

### ISSUE THREAD

**Issue by ynpl** [oliverkirk-sudo/WarpGPT#4]
proxy_pool_url的格式是什么样的呀

**Comment by oliverkirk-sudo** [comment]
代理池产生的链接，可以选填

**Comment by ynpl** [comment]
> 代理池产生的链接，可以选填

可能我没表述清楚, 我的本意是格式是什么样的?
xxx.xxx.xx:xxxx,还是http://账号:密码@ip:端口号

**Comment by oliverkirk-sudo** [comment]
等会我把文档写详细些

**Comment by oliverkirk-sudo** [comment]
http://api.proxy.ipidea.io/getProxyIp?num=10&return_type=json&lb=1&sb=0&flow=1&regions=us&protocol=http
这个样子的，因为代理池会设置ip白名单，如果你通过白名单里的ip访问这个链接就会自动扣流量，不需要账户名和密码
