### ISSUE TITLE
docker部署的，3.5可以用，4.0报500的错误，har包也上传了的，但arkose应该有点问题。

### ISSUE THREAD

**Issue by xiaosaaaa** [oliverkirk-sudo/WarpGPT#9]
[GIN-debug] [WARNING] You trusted all proxies, this is NOT safe. We recommend you to set a value.
Please check https://pkg.go.dev/github.com/gin-gonic/gin#readme-don-t-trust-all-proxies for details.
[GIN-debug] Listening and serving HTTP on 0.0.0.0:5000
time="2024-01-23 17:40:42" level=debug msg="未启动redis"
time="2024-01-23 17:43:08" level=debug msg=ProcessBackendProcess
time="2024-01-23 17:43:08" level=debug msg="BackendProcess createRequest"
time="2024-01-23 17:43:08" level=debug msg="BackendProcess addArkoseTokenIfNeeded"
time="2024-01-23 17:43:08" level=debug msg="BackendProcess buildHeaders"
time="2024-01-23 17:43:08" level=debug msg="BackendProcess setCookies"
time="2024-01-23 17:43:09" level=debug msg=CopyResponseHeaders
time="2024-01-23 17:43:09" level=debug msg="BackendProcess streamResponse"
[GIN] 2024/01/23 - 17:43:10 | 200 |  1.779648884s | x.x.x.x | POST     "/backend-api/conversation"
time="2024-01-23 17:43:25" level=debug msg=ProcessBackendProcess
time="2024-01-23 17:43:25" level=debug msg="BackendProcess createRequest"
time="2024-01-23 17:43:25" level=debug msg="BackendProcess addArkoseTokenIfNeeded"
time="2024-01-23 17:43:25" level=debug msg=GetArkoseToken
time="2024-01-23 17:43:25" level=warning msg="a valid HAR file with arkType \x04 required"
[GIN] 2024/01/23 - 17:43:25 | 500 |     244.943µs | x.x.x.x | POST     "/backend-api/conversation"
time="2024-01-23 17:43:42" level=debug msg=ProcessBackendProcess
time="2024-01-23 17:43:42" level=debug msg="BackendProcess createRequest"
time="2024-01-23 17:43:42" level=debug msg="BackendProcess addArkoseTokenIfNeeded"
time="2024-01-23 17:43:42" level=debug msg=GetArkoseToken
time="2024-01-23 17:43:42" level=warning msg="a valid HAR file with arkType \x04 required"
[GIN] 2024/01/23 - 17:43:42 | 500 |     230.614µs | x.x.x.x | POST     "/backend-api/conversation"

**Comment by xiaosaaaa** [comment]
发现问题了，我在服务器上传到harPool文件夹的har文件没有映射到容器的/app/harPool内，手动复制了一份进去就没问题了。
还有个问题，上面日志中显示未启动redis，我该如何启动呢。

**Comment by oliverkirk-sudo** [comment]
redis只对代理池有用，没有代理池不用管，没设置代理池就会显示Redis未启动

**Comment by xiaosaaaa** [comment]
> redis只对代理池有用，没有代理池不用管，没设置代理池就会显示Redis未启动

明白了，感谢。

**Comment by xiaosaaaa** [comment]
version: '3'
services:
  warp_gpt:
    image: warpgpt
    container_name: warp_gpt
    ports:
      - "5000:5000"
    volumes:
      - /root/WarpGPT/harPool:/app/harPool
    restart: unless-stopped

贴一个docker-compose.yml

**Comment by xiaosaaaa** [comment]
[GIN-debug] [WARNING] You trusted all proxies, this is NOT safe. We recommend you to set a value.
Please check https://pkg.go.dev/github.com/gin-gonic/gin#readme-don-t-trust-all-proxies for details.
[GIN-debug] Listening and serving HTTP on 0.0.0.0:5000
time="2024-01-24 06:05:12" level=debug msg="未启动redis"
time="2024-01-24 06:06:35" level=debug msg=ProcessBackendProcess
time="2024-01-24 06:06:35" level=debug msg="BackendProcess createRequest"
time="2024-01-24 06:06:35" level=debug msg="BackendProcess addArkoseTokenIfNeeded"
time="2024-01-24 06:06:35" level=debug msg=GetArkoseToken
success read chat4 arkose
success read chat4 arkose
time="2024-01-24 06:06:36" level=warning msg="captcha required"
[GIN] 2024/01/24 - 06:06:36 | 500 |  364.339803ms | x.x.x.x | POST     "/backend-api/conversation"
time="2024-01-24 06:06:47" level=debug msg=ProcessBackendProcess
time="2024-01-24 06:06:47" level=debug msg="BackendProcess createRequest"
time="2024-01-24 06:06:47" level=debug msg="BackendProcess addArkoseTokenIfNeeded"
time="2024-01-24 06:06:47" level=debug msg="BackendProcess buildHeaders"
time="2024-01-24 06:06:47" level=debug msg="BackendProcess setCookies"
time="2024-01-24 06:06:48" level=debug msg=CopyResponseHeaders
time="2024-01-24 06:06:48" level=debug msg="BackendProcess streamResponse"
[GIN] 2024/01/24 - 06:06:48 | 200 |  851.747206ms | x.x.x.x | POST     "/backend-api/conversation"

今天arkose是不是改算法了，又开始报500

**Comment by oliverkirk-sudo** [comment]
你ip黑了，time="2024-01-24 06:06:36" level=warning msg="captcha required"

**Comment by xiaosaaaa** [comment]
应该是openai风控又拉高了

**Comment by oliverkirk-sudo** [comment]
上代理咯

**Comment by oliverkirk-sudo** [comment]
试试套个warp

**Comment by xiaosaaaa** [comment]
ok
